### PR TITLE
Fix landscape mode

### PR DESCRIPTION
**Pull request by jacob-andersson**

### CODE REVIEW

**Comment by 3lvis** [comment]
ios simulator screen shot 23 apr 2015 15 13 22
ios simulator screen shot 23 apr 2015 15 13 20

**Comment by jacob-andersson** [comment]
@3lvis Yes: that is correct

**Comment by 3lvis** [comment]
@jacob-andersson: it's better than before but still, half of the leg is missing

**Comment by 3lvis** [comment]
@jacob-andersson will keep the issue until is fully fixed

**Comment by jacob-andersson** [comment]
@3lvis It is because of the image rendering mode that is set to keep aspect, which I believe is the best approach

**Comment by jacob-andersson** [comment]
@3lvis: How do you want it? In my opinion it does not make sense to mess with aspect ratio.

**Comment by 3lvis** [comment]
@jacob-andersson I see, I'll close the issue :)

**Pull request merged**
