### PR TITLE
Fix/media reload

### PR DESCRIPTION
**Pull request by jacob-andersson**

### CODE REVIEW

**Comment by 3lvis** [comment]
@jacob-andersson You didn't had to rename the project, you could just create a new target

**Comment by 3lvis** [comment]
dwqdq

**Comment by 3lvis** [comment]
@jacob-andersson code looks good but might be better to keep things consistent between projects. Keep the Pod project and just make a new target for Demo.

**Comment by 3lvis** [comment]
Example => https://github.com/hyperoslo/Contract/tree/master/Pod

**Comment by jacob-andersson** [comment]
Okidoki, will fix

**Comment by jacob-andersson** [comment]
@3lvis: Is this structure OK?

**Comment by 3lvis** [comment]
The idea is to have a `Tests` target for testing purposes and a `Demo` target for running the app.

**Comment by 3lvis** [comment]
Currently we have `DemoTests` and `Demo`, it works but not exactly what I had in mind :)

**Pull request merged**
